#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys
from .ttypes import *
AllDirectoryContents = -1
mapManagementNames = {
    0: "Managed",
    1: "Unmanaged",
}
mapFilestoreAreaToStr = {
    0: "ProjectStorage",
    3: "NativeFileLocation",
    2: "Share",
    1: "Production",
    5: "DataSource",
    7: "NativeUpload",
    6: "NativeCache",
    4: "ExternalTextStorage",
}
mapFeatureTypeToAreas = {
    1: [
        3,
        7,
    ],
    3: [
        4,
    ],
    2: [
        5,
    ],
    0: [
        0,
        1,
        2,
        6,
    ],
}
