#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys
import AdminAPIStructs.ttypes

from thrift.transport import TTransport
all_structs = []


class enAnnotationType(object):
    annotNone = 0
    annotHighlight = 1
    annotRedaction = 2
    annotText = 4
    annotComments = 8
    annotOval = 16
    annotRectangle = 32
    annotLine = 64
    annotArrow = 128
    annotHeaderFooter = 256
    annotInverseRedaction = 512
    annotAny = 32767
    annotLock = 65535

    _VALUES_TO_NAMES = {
        0: "annotNone",
        1: "annotHighlight",
        2: "annotRedaction",
        4: "annotText",
        8: "annotComments",
        16: "annotOval",
        32: "annotRectangle",
        64: "annotLine",
        128: "annotArrow",
        256: "annotHeaderFooter",
        512: "annotInverseRedaction",
        32767: "annotAny",
        65535: "annotLock",
    }

    _NAMES_TO_VALUES = {
        "annotNone": 0,
        "annotHighlight": 1,
        "annotRedaction": 2,
        "annotText": 4,
        "annotComments": 8,
        "annotOval": 16,
        "annotRectangle": 32,
        "annotLine": 64,
        "annotArrow": 128,
        "annotHeaderFooter": 256,
        "annotInverseRedaction": 512,
        "annotAny": 32767,
        "annotLock": 65535,
    }


class enAnnotationAlignment(object):
    alignLeft = 0
    alignCenter = 1
    alignRight = 2

    _VALUES_TO_NAMES = {
        0: "alignLeft",
        1: "alignCenter",
        2: "alignRight",
    }

    _NAMES_TO_VALUES = {
        "alignLeft": 0,
        "alignCenter": 1,
        "alignRight": 2,
    }


class enAnnotationSource(object):
    userCreated = 1
    massActionCreated = 2

    _VALUES_TO_NAMES = {
        1: "userCreated",
        2: "massActionCreated",
    }

    _NAMES_TO_VALUES = {
        "userCreated": 1,
        "massActionCreated": 2,
    }


class enAnnotationOptions(object):
    normal = 0
    semiTransparentRedaction = 1

    _VALUES_TO_NAMES = {
        0: "normal",
        1: "semiTransparentRedaction",
    }

    _NAMES_TO_VALUES = {
        "normal": 0,
        "semiTransparentRedaction": 1,
    }


class enPageBlockerType(object):
    blockerNone = 0
    blockerBlank = 1

    _VALUES_TO_NAMES = {
        0: "blockerNone",
        1: "blockerBlank",
    }

    _NAMES_TO_VALUES = {
        "blockerNone": 0,
        "blockerBlank": 1,
    }


class NativeRedactorType(object):
    Unknown = 0
    SpreadSheet = 1
    ScanOnly = 10
    ScanAndHash = 11
    Redaction = 20

    _VALUES_TO_NAMES = {
        0: "Unknown",
        1: "SpreadSheet",
        10: "ScanOnly",
        11: "ScanAndHash",
        20: "Redaction",
    }

    _NAMES_TO_VALUES = {
        "Unknown": 0,
        "SpreadSheet": 1,
        "ScanOnly": 10,
        "ScanAndHash": 11,
        "Redaction": 20,
    }


class AnnotationStyleInfo(object):
    """
    Attributes:
     - dFontHeight
     - sFontName
     - sFontColour
     - bBold
     - bItalic
     - bUnderline
    """


    def __init__(self, dFontHeight=12, sFontName="Calibri", sFontColour="#000000", bBold=False, bItalic=False, bUnderline=False,):
        self.dFontHeight = dFontHeight
        self.sFontName = sFontName
        self.sFontColour = sFontColour
        self.bBold = bBold
        self.bItalic = bItalic
        self.bUnderline = bUnderline

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 14:
                if ftype == TType.DOUBLE:
                    self.dFontHeight = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 15:
                if ftype == TType.STRING:
                    self.sFontName = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 16:
                if ftype == TType.STRING:
                    self.sFontColour = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 22:
                if ftype == TType.BOOL:
                    self.bBold = iprot.readBool()
                else:
                    iprot.skip(ftype)
            elif fid == 23:
                if ftype == TType.BOOL:
                    self.bItalic = iprot.readBool()
                else:
                    iprot.skip(ftype)
            elif fid == 28:
                if ftype == TType.BOOL:
                    self.bUnderline = iprot.readBool()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('AnnotationStyleInfo')
        if self.dFontHeight is not None:
            oprot.writeFieldBegin('dFontHeight', TType.DOUBLE, 14)
            oprot.writeDouble(self.dFontHeight)
            oprot.writeFieldEnd()
        if self.sFontName is not None:
            oprot.writeFieldBegin('sFontName', TType.STRING, 15)
            oprot.writeString(self.sFontName.encode('utf-8') if sys.version_info[0] == 2 else self.sFontName)
            oprot.writeFieldEnd()
        if self.sFontColour is not None:
            oprot.writeFieldBegin('sFontColour', TType.STRING, 16)
            oprot.writeString(self.sFontColour.encode('utf-8') if sys.version_info[0] == 2 else self.sFontColour)
            oprot.writeFieldEnd()
        if self.bBold is not None:
            oprot.writeFieldBegin('bBold', TType.BOOL, 22)
            oprot.writeBool(self.bBold)
            oprot.writeFieldEnd()
        if self.bItalic is not None:
            oprot.writeFieldBegin('bItalic', TType.BOOL, 23)
            oprot.writeBool(self.bItalic)
            oprot.writeFieldEnd()
        if self.bUnderline is not None:
            oprot.writeFieldBegin('bUnderline', TType.BOOL, 28)
            oprot.writeBool(self.bUnderline)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class Annotation(object):
    """
    Attributes:
     - eType
     - dXPos
     - dYPos
     - dWidth
     - dHeight
     - sText
     - sFillColour
     - sLineColour
     - iRotation
     - dLineOpacity
     - dFillOpacity
     - dLineWidth
     - dFontHeight
     - sFontName
     - sFontColour
     - iOrder
     - sCreatedBy
     - sTimeCreated
     - sModifiedBy
     - sModifiedTime
     - iPageLevelID
     - bBold
     - bItalic
     - dRotation
     - eAlign
     - lModifiedByID
     - lCreatedByID
     - bUnderline
     - lTextBottom
     - dOffsetRotation
     - bAutoWrap
     - sReasonCategory
     - sFoundValue
     - sSearchedValue
     - iConfidence
     - eSource
     - lFormFieldID
    """


    def __init__(self, eType=None, dXPos=None, dYPos=None, dWidth=None, dHeight=None, sText=None, sFillColour=None, sLineColour=None, iRotation=None, dLineOpacity=None, dFillOpacity=None, dLineWidth=None, dFontHeight=None, sFontName=None, sFontColour=None, iOrder=None, sCreatedBy="", sTimeCreated="", sModifiedBy="", sModifiedTime="", iPageLevelID=None, bBold=False, bItalic=False, dRotation=0, eAlign=0, lModifiedByID=0, lCreatedByID=0, bUnderline=False, lTextBottom=0, dOffsetRotation=0, bAutoWrap=False, sReasonCategory=None, sFoundValue=None, sSearchedValue=None, iConfidence=None, eSource=1, lFormFieldID=None,):
        self.eType = eType
        self.dXPos = dXPos
        self.dYPos = dYPos
        self.dWidth = dWidth
        self.dHeight = dHeight
        self.sText = sText
        self.sFillColour = sFillColour
        self.sLineColour = sLineColour
        self.iRotation = iRotation
        self.dLineOpacity = dLineOpacity
        self.dFillOpacity = dFillOpacity
        self.dLineWidth = dLineWidth
        self.dFontHeight = dFontHeight
        self.sFontName = sFontName
        self.sFontColour = sFontColour
        self.iOrder = iOrder
        self.sCreatedBy = sCreatedBy
        self.sTimeCreated = sTimeCreated
        self.sModifiedBy = sModifiedBy
        self.sModifiedTime = sModifiedTime
        self.iPageLevelID = iPageLevelID
        self.bBold = bBold
        self.bItalic = bItalic
        self.dRotation = dRotation
        self.eAlign = eAlign
        self.lModifiedByID = lModifiedByID
        self.lCreatedByID = lCreatedByID
        self.bUnderline = bUnderline
        self.lTextBottom = lTextBottom
        self.dOffsetRotation = dOffsetRotation
        self.bAutoWrap = bAutoWrap
        self.sReasonCategory = sReasonCategory
        self.sFoundValue = sFoundValue
        self.sSearchedValue = sSearchedValue
        self.iConfidence = iConfidence
        self.eSource = eSource
        self.lFormFieldID = lFormFieldID

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.eType = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.DOUBLE:
                    self.dXPos = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.DOUBLE:
                    self.dYPos = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.DOUBLE:
                    self.dWidth = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.DOUBLE:
                    self.dHeight = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 6:
                if ftype == TType.STRING:
                    self.sText = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 7:
                if ftype == TType.STRING:
                    self.sFillColour = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 8:
                if ftype == TType.STRING:
                    self.sLineColour = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 9:
                if ftype == TType.I32:
                    self.iRotation = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 10:
                if ftype == TType.DOUBLE:
                    self.dLineOpacity = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 11:
                if ftype == TType.DOUBLE:
                    self.dFillOpacity = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 13:
                if ftype == TType.DOUBLE:
                    self.dLineWidth = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 14:
                if ftype == TType.DOUBLE:
                    self.dFontHeight = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 15:
                if ftype == TType.STRING:
                    self.sFontName = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 16:
                if ftype == TType.STRING:
                    self.sFontColour = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 12:
                if ftype == TType.I32:
                    self.iOrder = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 17:
                if ftype == TType.STRING:
                    self.sCreatedBy = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 18:
                if ftype == TType.STRING:
                    self.sTimeCreated = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 19:
                if ftype == TType.STRING:
                    self.sModifiedBy = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 20:
                if ftype == TType.STRING:
                    self.sModifiedTime = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 21:
                if ftype == TType.I32:
                    self.iPageLevelID = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 22:
                if ftype == TType.BOOL:
                    self.bBold = iprot.readBool()
                else:
                    iprot.skip(ftype)
            elif fid == 23:
                if ftype == TType.BOOL:
                    self.bItalic = iprot.readBool()
                else:
                    iprot.skip(ftype)
            elif fid == 24:
                if ftype == TType.DOUBLE:
                    self.dRotation = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 25:
                if ftype == TType.I32:
                    self.eAlign = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 26:
                if ftype == TType.I64:
                    self.lModifiedByID = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 27:
                if ftype == TType.I64:
                    self.lCreatedByID = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 28:
                if ftype == TType.BOOL:
                    self.bUnderline = iprot.readBool()
                else:
                    iprot.skip(ftype)
            elif fid == 29:
                if ftype == TType.I64:
                    self.lTextBottom = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 30:
                if ftype == TType.DOUBLE:
                    self.dOffsetRotation = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 105:
                if ftype == TType.BOOL:
                    self.bAutoWrap = iprot.readBool()
                else:
                    iprot.skip(ftype)
            elif fid == 50:
                if ftype == TType.STRING:
                    self.sReasonCategory = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 51:
                if ftype == TType.STRING:
                    self.sFoundValue = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 52:
                if ftype == TType.STRING:
                    self.sSearchedValue = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 53:
                if ftype == TType.I32:
                    self.iConfidence = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 54:
                if ftype == TType.I32:
                    self.eSource = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 500:
                if ftype == TType.I64:
                    self.lFormFieldID = iprot.readI64()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('Annotation')
        if self.eType is not None:
            oprot.writeFieldBegin('eType', TType.I32, 1)
            oprot.writeI32(self.eType)
            oprot.writeFieldEnd()
        if self.dXPos is not None:
            oprot.writeFieldBegin('dXPos', TType.DOUBLE, 2)
            oprot.writeDouble(self.dXPos)
            oprot.writeFieldEnd()
        if self.dYPos is not None:
            oprot.writeFieldBegin('dYPos', TType.DOUBLE, 3)
            oprot.writeDouble(self.dYPos)
            oprot.writeFieldEnd()
        if self.dWidth is not None:
            oprot.writeFieldBegin('dWidth', TType.DOUBLE, 4)
            oprot.writeDouble(self.dWidth)
            oprot.writeFieldEnd()
        if self.dHeight is not None:
            oprot.writeFieldBegin('dHeight', TType.DOUBLE, 5)
            oprot.writeDouble(self.dHeight)
            oprot.writeFieldEnd()
        if self.sText is not None:
            oprot.writeFieldBegin('sText', TType.STRING, 6)
            oprot.writeString(self.sText.encode('utf-8') if sys.version_info[0] == 2 else self.sText)
            oprot.writeFieldEnd()
        if self.sFillColour is not None:
            oprot.writeFieldBegin('sFillColour', TType.STRING, 7)
            oprot.writeString(self.sFillColour.encode('utf-8') if sys.version_info[0] == 2 else self.sFillColour)
            oprot.writeFieldEnd()
        if self.sLineColour is not None:
            oprot.writeFieldBegin('sLineColour', TType.STRING, 8)
            oprot.writeString(self.sLineColour.encode('utf-8') if sys.version_info[0] == 2 else self.sLineColour)
            oprot.writeFieldEnd()
        if self.iRotation is not None:
            oprot.writeFieldBegin('iRotation', TType.I32, 9)
            oprot.writeI32(self.iRotation)
            oprot.writeFieldEnd()
        if self.dLineOpacity is not None:
            oprot.writeFieldBegin('dLineOpacity', TType.DOUBLE, 10)
            oprot.writeDouble(self.dLineOpacity)
            oprot.writeFieldEnd()
        if self.dFillOpacity is not None:
            oprot.writeFieldBegin('dFillOpacity', TType.DOUBLE, 11)
            oprot.writeDouble(self.dFillOpacity)
            oprot.writeFieldEnd()
        if self.iOrder is not None:
            oprot.writeFieldBegin('iOrder', TType.I32, 12)
            oprot.writeI32(self.iOrder)
            oprot.writeFieldEnd()
        if self.dLineWidth is not None:
            oprot.writeFieldBegin('dLineWidth', TType.DOUBLE, 13)
            oprot.writeDouble(self.dLineWidth)
            oprot.writeFieldEnd()
        if self.dFontHeight is not None:
            oprot.writeFieldBegin('dFontHeight', TType.DOUBLE, 14)
            oprot.writeDouble(self.dFontHeight)
            oprot.writeFieldEnd()
        if self.sFontName is not None:
            oprot.writeFieldBegin('sFontName', TType.STRING, 15)
            oprot.writeString(self.sFontName.encode('utf-8') if sys.version_info[0] == 2 else self.sFontName)
            oprot.writeFieldEnd()
        if self.sFontColour is not None:
            oprot.writeFieldBegin('sFontColour', TType.STRING, 16)
            oprot.writeString(self.sFontColour.encode('utf-8') if sys.version_info[0] == 2 else self.sFontColour)
            oprot.writeFieldEnd()
        if self.sCreatedBy is not None:
            oprot.writeFieldBegin('sCreatedBy', TType.STRING, 17)
            oprot.writeString(self.sCreatedBy.encode('utf-8') if sys.version_info[0] == 2 else self.sCreatedBy)
            oprot.writeFieldEnd()
        if self.sTimeCreated is not None:
            oprot.writeFieldBegin('sTimeCreated', TType.STRING, 18)
            oprot.writeString(self.sTimeCreated.encode('utf-8') if sys.version_info[0] == 2 else self.sTimeCreated)
            oprot.writeFieldEnd()
        if self.sModifiedBy is not None:
            oprot.writeFieldBegin('sModifiedBy', TType.STRING, 19)
            oprot.writeString(self.sModifiedBy.encode('utf-8') if sys.version_info[0] == 2 else self.sModifiedBy)
            oprot.writeFieldEnd()
        if self.sModifiedTime is not None:
            oprot.writeFieldBegin('sModifiedTime', TType.STRING, 20)
            oprot.writeString(self.sModifiedTime.encode('utf-8') if sys.version_info[0] == 2 else self.sModifiedTime)
            oprot.writeFieldEnd()
        if self.iPageLevelID is not None:
            oprot.writeFieldBegin('iPageLevelID', TType.I32, 21)
            oprot.writeI32(self.iPageLevelID)
            oprot.writeFieldEnd()
        if self.bBold is not None:
            oprot.writeFieldBegin('bBold', TType.BOOL, 22)
            oprot.writeBool(self.bBold)
            oprot.writeFieldEnd()
        if self.bItalic is not None:
            oprot.writeFieldBegin('bItalic', TType.BOOL, 23)
            oprot.writeBool(self.bItalic)
            oprot.writeFieldEnd()
        if self.dRotation is not None:
            oprot.writeFieldBegin('dRotation', TType.DOUBLE, 24)
            oprot.writeDouble(self.dRotation)
            oprot.writeFieldEnd()
        if self.eAlign is not None:
            oprot.writeFieldBegin('eAlign', TType.I32, 25)
            oprot.writeI32(self.eAlign)
            oprot.writeFieldEnd()
        if self.lModifiedByID is not None:
            oprot.writeFieldBegin('lModifiedByID', TType.I64, 26)
            oprot.writeI64(self.lModifiedByID)
            oprot.writeFieldEnd()
        if self.lCreatedByID is not None:
            oprot.writeFieldBegin('lCreatedByID', TType.I64, 27)
            oprot.writeI64(self.lCreatedByID)
            oprot.writeFieldEnd()
        if self.bUnderline is not None:
            oprot.writeFieldBegin('bUnderline', TType.BOOL, 28)
            oprot.writeBool(self.bUnderline)
            oprot.writeFieldEnd()
        if self.lTextBottom is not None:
            oprot.writeFieldBegin('lTextBottom', TType.I64, 29)
            oprot.writeI64(self.lTextBottom)
            oprot.writeFieldEnd()
        if self.dOffsetRotation is not None:
            oprot.writeFieldBegin('dOffsetRotation', TType.DOUBLE, 30)
            oprot.writeDouble(self.dOffsetRotation)
            oprot.writeFieldEnd()
        if self.sReasonCategory is not None:
            oprot.writeFieldBegin('sReasonCategory', TType.STRING, 50)
            oprot.writeString(self.sReasonCategory.encode('utf-8') if sys.version_info[0] == 2 else self.sReasonCategory)
            oprot.writeFieldEnd()
        if self.sFoundValue is not None:
            oprot.writeFieldBegin('sFoundValue', TType.STRING, 51)
            oprot.writeString(self.sFoundValue.encode('utf-8') if sys.version_info[0] == 2 else self.sFoundValue)
            oprot.writeFieldEnd()
        if self.sSearchedValue is not None:
            oprot.writeFieldBegin('sSearchedValue', TType.STRING, 52)
            oprot.writeString(self.sSearchedValue.encode('utf-8') if sys.version_info[0] == 2 else self.sSearchedValue)
            oprot.writeFieldEnd()
        if self.iConfidence is not None:
            oprot.writeFieldBegin('iConfidence', TType.I32, 53)
            oprot.writeI32(self.iConfidence)
            oprot.writeFieldEnd()
        if self.eSource is not None:
            oprot.writeFieldBegin('eSource', TType.I32, 54)
            oprot.writeI32(self.eSource)
            oprot.writeFieldEnd()
        if self.bAutoWrap is not None:
            oprot.writeFieldBegin('bAutoWrap', TType.BOOL, 105)
            oprot.writeBool(self.bAutoWrap)
            oprot.writeFieldEnd()
        if self.lFormFieldID is not None:
            oprot.writeFieldBegin('lFormFieldID', TType.I64, 500)
            oprot.writeI64(self.lFormFieldID)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class AnnotationData(object):
    """
    Attributes:
     - aAnnots
     - iPageLevelIDCount
     - ePageBlocker
     - sPageBlockerColour
     - lPageNumber
    """


    def __init__(self, aAnnots=None, iPageLevelIDCount=None, ePageBlocker=0, sPageBlockerColour=None, lPageNumber=None,):
        self.aAnnots = aAnnots
        self.iPageLevelIDCount = iPageLevelIDCount
        self.ePageBlocker = ePageBlocker
        self.sPageBlockerColour = sPageBlockerColour
        self.lPageNumber = lPageNumber

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.LIST:
                    self.aAnnots = []
                    (_etype3, _size0) = iprot.readListBegin()
                    for _i4 in range(_size0):
                        _elem5 = Annotation()
                        _elem5.read(iprot)
                        self.aAnnots.append(_elem5)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.iPageLevelIDCount = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I32:
                    self.ePageBlocker = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.STRING:
                    self.sPageBlockerColour = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.I64:
                    self.lPageNumber = iprot.readI64()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('AnnotationData')
        if self.aAnnots is not None:
            oprot.writeFieldBegin('aAnnots', TType.LIST, 1)
            oprot.writeListBegin(TType.STRUCT, len(self.aAnnots))
            for iter6 in self.aAnnots:
                iter6.write(oprot)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.iPageLevelIDCount is not None:
            oprot.writeFieldBegin('iPageLevelIDCount', TType.I32, 2)
            oprot.writeI32(self.iPageLevelIDCount)
            oprot.writeFieldEnd()
        if self.ePageBlocker is not None:
            oprot.writeFieldBegin('ePageBlocker', TType.I32, 3)
            oprot.writeI32(self.ePageBlocker)
            oprot.writeFieldEnd()
        if self.sPageBlockerColour is not None:
            oprot.writeFieldBegin('sPageBlockerColour', TType.STRING, 4)
            oprot.writeString(self.sPageBlockerColour.encode('utf-8') if sys.version_info[0] == 2 else self.sPageBlockerColour)
            oprot.writeFieldEnd()
        if self.lPageNumber is not None:
            oprot.writeFieldBegin('lPageNumber', TType.I64, 5)
            oprot.writeI64(self.lPageNumber)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class PageAnnotations(object):
    """
    Attributes:
     - ID
     - lObjectID
     - lFieldID
     - lSetID
     - sDocument
     - sPage
     - oAnnotData
    """


    def __init__(self, ID=None, lObjectID=None, lFieldID=None, lSetID=None, sDocument=None, sPage=None, oAnnotData=None,):
        self.ID = ID
        self.lObjectID = lObjectID
        self.lFieldID = lFieldID
        self.lSetID = lSetID
        self.sDocument = sDocument
        self.sPage = sPage
        self.oAnnotData = oAnnotData

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I64:
                    self.ID = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I64:
                    self.lObjectID = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I64:
                    self.lFieldID = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.I64:
                    self.lSetID = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.STRING:
                    self.sDocument = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 6:
                if ftype == TType.STRING:
                    self.sPage = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 7:
                if ftype == TType.STRUCT:
                    self.oAnnotData = AnnotationData()
                    self.oAnnotData.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('PageAnnotations')
        if self.ID is not None:
            oprot.writeFieldBegin('ID', TType.I64, 1)
            oprot.writeI64(self.ID)
            oprot.writeFieldEnd()
        if self.lObjectID is not None:
            oprot.writeFieldBegin('lObjectID', TType.I64, 2)
            oprot.writeI64(self.lObjectID)
            oprot.writeFieldEnd()
        if self.lFieldID is not None:
            oprot.writeFieldBegin('lFieldID', TType.I64, 3)
            oprot.writeI64(self.lFieldID)
            oprot.writeFieldEnd()
        if self.lSetID is not None:
            oprot.writeFieldBegin('lSetID', TType.I64, 4)
            oprot.writeI64(self.lSetID)
            oprot.writeFieldEnd()
        if self.sDocument is not None:
            oprot.writeFieldBegin('sDocument', TType.STRING, 5)
            oprot.writeString(self.sDocument.encode('utf-8') if sys.version_info[0] == 2 else self.sDocument)
            oprot.writeFieldEnd()
        if self.sPage is not None:
            oprot.writeFieldBegin('sPage', TType.STRING, 6)
            oprot.writeString(self.sPage.encode('utf-8') if sys.version_info[0] == 2 else self.sPage)
            oprot.writeFieldEnd()
        if self.oAnnotData is not None:
            oprot.writeFieldBegin('oAnnotData', TType.STRUCT, 7)
            self.oAnnotData.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class AnnotationDateRange(object):
    """
    Attributes:
     - sStartDate
     - sEndDate
    """


    def __init__(self, sStartDate=None, sEndDate=None,):
        self.sStartDate = sStartDate
        self.sEndDate = sEndDate

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.sStartDate = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRING:
                    self.sEndDate = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('AnnotationDateRange')
        if self.sStartDate is not None:
            oprot.writeFieldBegin('sStartDate', TType.STRING, 1)
            oprot.writeString(self.sStartDate.encode('utf-8') if sys.version_info[0] == 2 else self.sStartDate)
            oprot.writeFieldEnd()
        if self.sEndDate is not None:
            oprot.writeFieldBegin('sEndDate', TType.STRING, 2)
            oprot.writeString(self.sEndDate.encode('utf-8') if sys.version_info[0] == 2 else self.sEndDate)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class AnnotationLimiter(object):
    """
    Attributes:
     - aCreatedByUserGroups
     - oModifiedDate
     - oCreatedDate
     - setAnnotationTypes
    """


    def __init__(self, aCreatedByUserGroups=None, oModifiedDate=None, oCreatedDate=None, setAnnotationTypes=None,):
        self.aCreatedByUserGroups = aCreatedByUserGroups
        self.oModifiedDate = oModifiedDate
        self.oCreatedDate = oCreatedDate
        self.setAnnotationTypes = setAnnotationTypes

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.SET:
                    self.aCreatedByUserGroups = set()
                    (_etype10, _size7) = iprot.readSetBegin()
                    for _i11 in range(_size7):
                        _elem12 = iprot.readI64()
                        self.aCreatedByUserGroups.add(_elem12)
                    iprot.readSetEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRUCT:
                    self.oModifiedDate = AnnotationDateRange()
                    self.oModifiedDate.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRUCT:
                    self.oCreatedDate = AnnotationDateRange()
                    self.oCreatedDate.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.SET:
                    self.setAnnotationTypes = set()
                    (_etype16, _size13) = iprot.readSetBegin()
                    for _i17 in range(_size13):
                        _elem18 = iprot.readI32()
                        self.setAnnotationTypes.add(_elem18)
                    iprot.readSetEnd()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('AnnotationLimiter')
        if self.aCreatedByUserGroups is not None:
            oprot.writeFieldBegin('aCreatedByUserGroups', TType.SET, 1)
            oprot.writeSetBegin(TType.I64, len(self.aCreatedByUserGroups))
            for iter19 in self.aCreatedByUserGroups:
                oprot.writeI64(iter19)
            oprot.writeSetEnd()
            oprot.writeFieldEnd()
        if self.oModifiedDate is not None:
            oprot.writeFieldBegin('oModifiedDate', TType.STRUCT, 2)
            self.oModifiedDate.write(oprot)
            oprot.writeFieldEnd()
        if self.oCreatedDate is not None:
            oprot.writeFieldBegin('oCreatedDate', TType.STRUCT, 3)
            self.oCreatedDate.write(oprot)
            oprot.writeFieldEnd()
        if self.setAnnotationTypes is not None:
            oprot.writeFieldBegin('setAnnotationTypes', TType.SET, 4)
            oprot.writeSetBegin(TType.I32, len(self.setAnnotationTypes))
            for iter20 in self.setAnnotationTypes:
                oprot.writeI32(iter20)
            oprot.writeSetEnd()
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class TextImageBBox(object):
    """
    Attributes:
     - TopLeftX
     - TopLeftY
     - BottomRightX
     - BottomRightY
    """


    def __init__(self, TopLeftX=0, TopLeftY=0, BottomRightX=0, BottomRightY=0,):
        self.TopLeftX = TopLeftX
        self.TopLeftY = TopLeftY
        self.BottomRightX = BottomRightX
        self.BottomRightY = BottomRightY

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I64:
                    self.TopLeftX = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I64:
                    self.TopLeftY = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I64:
                    self.BottomRightX = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.I64:
                    self.BottomRightY = iprot.readI64()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('TextImageBBox')
        if self.TopLeftX is not None:
            oprot.writeFieldBegin('TopLeftX', TType.I64, 1)
            oprot.writeI64(self.TopLeftX)
            oprot.writeFieldEnd()
        if self.TopLeftY is not None:
            oprot.writeFieldBegin('TopLeftY', TType.I64, 2)
            oprot.writeI64(self.TopLeftY)
            oprot.writeFieldEnd()
        if self.BottomRightX is not None:
            oprot.writeFieldBegin('BottomRightX', TType.I64, 3)
            oprot.writeI64(self.BottomRightX)
            oprot.writeFieldEnd()
        if self.BottomRightY is not None:
            oprot.writeFieldBegin('BottomRightY', TType.I64, 4)
            oprot.writeI64(self.BottomRightY)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class TextImageHits(object):
    """
    Attributes:
     - image
     - page_bbox
     - rotation
     - hit_bboxes
     - key
     - confidence
    """


    def __init__(self, image=None, page_bbox=None, rotation=None, hit_bboxes=None, key=None, confidence=None,):
        self.image = image
        self.page_bbox = page_bbox
        self.rotation = rotation
        self.hit_bboxes = hit_bboxes
        self.key = key
        self.confidence = confidence

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.image = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRUCT:
                    self.page_bbox = TextImageBBox()
                    self.page_bbox.read(iprot)
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.I32:
                    self.rotation = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.LIST:
                    self.hit_bboxes = []
                    (_etype24, _size21) = iprot.readListBegin()
                    for _i25 in range(_size21):
                        _elem26 = TextImageBBox()
                        _elem26.read(iprot)
                        self.hit_bboxes.append(_elem26)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.STRING:
                    self.key = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 6:
                if ftype == TType.DOUBLE:
                    self.confidence = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('TextImageHits')
        if self.image is not None:
            oprot.writeFieldBegin('image', TType.STRING, 1)
            oprot.writeString(self.image.encode('utf-8') if sys.version_info[0] == 2 else self.image)
            oprot.writeFieldEnd()
        if self.page_bbox is not None:
            oprot.writeFieldBegin('page_bbox', TType.STRUCT, 2)
            self.page_bbox.write(oprot)
            oprot.writeFieldEnd()
        if self.rotation is not None:
            oprot.writeFieldBegin('rotation', TType.I32, 3)
            oprot.writeI32(self.rotation)
            oprot.writeFieldEnd()
        if self.hit_bboxes is not None:
            oprot.writeFieldBegin('hit_bboxes', TType.LIST, 4)
            oprot.writeListBegin(TType.STRUCT, len(self.hit_bboxes))
            for iter27 in self.hit_bboxes:
                iter27.write(oprot)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.key is not None:
            oprot.writeFieldBegin('key', TType.STRING, 5)
            oprot.writeString(self.key.encode('utf-8') if sys.version_info[0] == 2 else self.key)
            oprot.writeFieldEnd()
        if self.confidence is not None:
            oprot.writeFieldBegin('confidence', TType.DOUBLE, 6)
            oprot.writeDouble(self.confidence)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class RegularExpression(object):
    """
    Attributes:
     - Name
     - Expression
    """


    def __init__(self, Name=None, Expression=None,):
        self.Name = Name
        self.Expression = Expression

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.Name = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRING:
                    self.Expression = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('RegularExpression')
        if self.Name is not None:
            oprot.writeFieldBegin('Name', TType.STRING, 1)
            oprot.writeString(self.Name.encode('utf-8') if sys.version_info[0] == 2 else self.Name)
            oprot.writeFieldEnd()
        if self.Expression is not None:
            oprot.writeFieldBegin('Expression', TType.STRING, 2)
            oprot.writeString(self.Expression.encode('utf-8') if sys.version_info[0] == 2 else self.Expression)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class SpreadSheetRedactions(object):
    """
    Attributes:
     - SheetNumber
     - RedactionColour
     - SelectorList
     - SearchValues
     - ConfidenceThreshold
     - ReplacementText
    """


    def __init__(self, SheetNumber=None, RedactionColour=None, SelectorList=None, SearchValues=None, ConfidenceThreshold=100, ReplacementText=None,):
        self.SheetNumber = SheetNumber
        self.RedactionColour = RedactionColour
        self.SelectorList = SelectorList
        self.SearchValues = SearchValues
        self.ConfidenceThreshold = ConfidenceThreshold
        self.ReplacementText = ReplacementText

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.SheetNumber = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.RedactionColour = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.LIST:
                    self.SelectorList = []
                    (_etype31, _size28) = iprot.readListBegin()
                    for _i32 in range(_size28):
                        _elem33 = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                        self.SelectorList.append(_elem33)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.LIST:
                    self.SearchValues = []
                    (_etype37, _size34) = iprot.readListBegin()
                    for _i38 in range(_size34):
                        _elem39 = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                        self.SearchValues.append(_elem39)
                    iprot.readListEnd()
                else:
                    iprot.skip(ftype)
            elif fid == 6:
                if ftype == TType.I32:
                    self.ConfidenceThreshold = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 8:
                if ftype == TType.STRING:
                    self.ReplacementText = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('SpreadSheetRedactions')
        if self.SheetNumber is not None:
            oprot.writeFieldBegin('SheetNumber', TType.I32, 1)
            oprot.writeI32(self.SheetNumber)
            oprot.writeFieldEnd()
        if self.RedactionColour is not None:
            oprot.writeFieldBegin('RedactionColour', TType.I32, 2)
            oprot.writeI32(self.RedactionColour)
            oprot.writeFieldEnd()
        if self.SelectorList is not None:
            oprot.writeFieldBegin('SelectorList', TType.LIST, 3)
            oprot.writeListBegin(TType.STRING, len(self.SelectorList))
            for iter40 in self.SelectorList:
                oprot.writeString(iter40.encode('utf-8') if sys.version_info[0] == 2 else iter40)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.SearchValues is not None:
            oprot.writeFieldBegin('SearchValues', TType.LIST, 4)
            oprot.writeListBegin(TType.STRING, len(self.SearchValues))
            for iter41 in self.SearchValues:
                oprot.writeString(iter41.encode('utf-8') if sys.version_info[0] == 2 else iter41)
            oprot.writeListEnd()
            oprot.writeFieldEnd()
        if self.ConfidenceThreshold is not None:
            oprot.writeFieldBegin('ConfidenceThreshold', TType.I32, 6)
            oprot.writeI32(self.ConfidenceThreshold)
            oprot.writeFieldEnd()
        if self.ReplacementText is not None:
            oprot.writeFieldBegin('ReplacementText', TType.STRING, 8)
            oprot.writeString(self.ReplacementText.encode('utf-8') if sys.version_info[0] == 2 else self.ReplacementText)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class NativeRedactorMessage(object):
    """
    Attributes:
     - JobID
     - Type
     - FeedbackQueue
     - Message
     - RecordID
     - ProjectID
    """


    def __init__(self, JobID=None, Type=None, FeedbackQueue=None, Message=None, RecordID=None, ProjectID=None,):
        self.JobID = JobID
        self.Type = Type
        self.FeedbackQueue = FeedbackQueue
        self.Message = Message
        self.RecordID = RecordID
        self.ProjectID = ProjectID

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I64:
                    self.JobID = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.Type = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.FeedbackQueue = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.STRING:
                    self.Message = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 5:
                if ftype == TType.I64:
                    self.RecordID = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 6:
                if ftype == TType.I64:
                    self.ProjectID = iprot.readI64()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('NativeRedactorMessage')
        if self.JobID is not None:
            oprot.writeFieldBegin('JobID', TType.I64, 1)
            oprot.writeI64(self.JobID)
            oprot.writeFieldEnd()
        if self.Type is not None:
            oprot.writeFieldBegin('Type', TType.I32, 2)
            oprot.writeI32(self.Type)
            oprot.writeFieldEnd()
        if self.FeedbackQueue is not None:
            oprot.writeFieldBegin('FeedbackQueue', TType.STRING, 3)
            oprot.writeString(self.FeedbackQueue.encode('utf-8') if sys.version_info[0] == 2 else self.FeedbackQueue)
            oprot.writeFieldEnd()
        if self.Message is not None:
            oprot.writeFieldBegin('Message', TType.STRING, 4)
            oprot.writeString(self.Message.encode('utf-8') if sys.version_info[0] == 2 else self.Message)
            oprot.writeFieldEnd()
        if self.RecordID is not None:
            oprot.writeFieldBegin('RecordID', TType.I64, 5)
            oprot.writeI64(self.RecordID)
            oprot.writeFieldEnd()
        if self.ProjectID is not None:
            oprot.writeFieldBegin('ProjectID', TType.I64, 6)
            oprot.writeI64(self.ProjectID)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class NativeRedactionResult(object):
    """
    Attributes:
     - Success
     - Message
    """


    def __init__(self, Success=None, Message=None,):
        self.Success = Success
        self.Message = Message

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.BOOL:
                    self.Success = iprot.readBool()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRING:
                    self.Message = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('NativeRedactionResult')
        if self.Success is not None:
            oprot.writeFieldBegin('Success', TType.BOOL, 1)
            oprot.writeBool(self.Success)
            oprot.writeFieldEnd()
        if self.Message is not None:
            oprot.writeFieldBegin('Message', TType.STRING, 2)
            oprot.writeString(self.Message.encode('utf-8') if sys.version_info[0] == 2 else self.Message)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class SpreadSheetRedactorMessage(object):
    """
    Attributes:
     - SourceFile
     - TargetFile
     - Redactions
    """


    def __init__(self, SourceFile=None, TargetFile=None, Redactions=None,):
        self.SourceFile = SourceFile
        self.TargetFile = TargetFile
        self.Redactions = Redactions

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.STRING:
                    self.SourceFile = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRING:
                    self.TargetFile = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRUCT:
                    self.Redactions = SpreadSheetRedactions()
                    self.Redactions.read(iprot)
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('SpreadSheetRedactorMessage')
        if self.SourceFile is not None:
            oprot.writeFieldBegin('SourceFile', TType.STRING, 1)
            oprot.writeString(self.SourceFile.encode('utf-8') if sys.version_info[0] == 2 else self.SourceFile)
            oprot.writeFieldEnd()
        if self.TargetFile is not None:
            oprot.writeFieldBegin('TargetFile', TType.STRING, 2)
            oprot.writeString(self.TargetFile.encode('utf-8') if sys.version_info[0] == 2 else self.TargetFile)
            oprot.writeFieldEnd()
        if self.Redactions is not None:
            oprot.writeFieldBegin('Redactions', TType.STRUCT, 3)
            self.Redactions.write(oprot)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class RedactionList(object):
    """
    Attributes:
     - lID
     - sName
    """


    def __init__(self, lID=None, sName=None,):
        self.lID = lID
        self.sName = sName

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I64:
                    self.lID = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.STRING:
                    self.sName = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('RedactionList')
        if self.lID is not None:
            oprot.writeFieldBegin('lID', TType.I64, 1)
            oprot.writeI64(self.lID)
            oprot.writeFieldEnd()
        if self.sName is not None:
            oprot.writeFieldBegin('sName', TType.STRING, 2)
            oprot.writeString(self.sName.encode('utf-8') if sys.version_info[0] == 2 else self.sName)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)


class RedactionListItem(object):
    """
    Attributes:
     - lID
     - lListID
     - sText
     - sReason
    """


    def __init__(self, lID=None, lListID=None, sText=None, sReason=None,):
        self.lID = lID
        self.lListID = lListID
        self.sText = sText
        self.sReason = sReason

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I64:
                    self.lID = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I64:
                    self.lListID = iprot.readI64()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.STRING:
                    self.sText = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.STRING:
                    self.sReason = iprot.readString().decode('utf-8') if sys.version_info[0] == 2 else iprot.readString()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('RedactionListItem')
        if self.lID is not None:
            oprot.writeFieldBegin('lID', TType.I64, 1)
            oprot.writeI64(self.lID)
            oprot.writeFieldEnd()
        if self.lListID is not None:
            oprot.writeFieldBegin('lListID', TType.I64, 2)
            oprot.writeI64(self.lListID)
            oprot.writeFieldEnd()
        if self.sText is not None:
            oprot.writeFieldBegin('sText', TType.STRING, 3)
            oprot.writeString(self.sText.encode('utf-8') if sys.version_info[0] == 2 else self.sText)
            oprot.writeFieldEnd()
        if self.sReason is not None:
            oprot.writeFieldBegin('sReason', TType.STRING, 4)
            oprot.writeString(self.sReason.encode('utf-8') if sys.version_info[0] == 2 else self.sReason)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(AnnotationStyleInfo)
AnnotationStyleInfo.thrift_spec = (
    None,  # 0
    None,  # 1
    None,  # 2
    None,  # 3
    None,  # 4
    None,  # 5
    None,  # 6
    None,  # 7
    None,  # 8
    None,  # 9
    None,  # 10
    None,  # 11
    None,  # 12
    None,  # 13
    (14, TType.DOUBLE, 'dFontHeight', None, 12, ),  # 14
    (15, TType.STRING, 'sFontName', 'UTF8', "Calibri", ),  # 15
    (16, TType.STRING, 'sFontColour', 'UTF8', "#000000", ),  # 16
    None,  # 17
    None,  # 18
    None,  # 19
    None,  # 20
    None,  # 21
    (22, TType.BOOL, 'bBold', None, False, ),  # 22
    (23, TType.BOOL, 'bItalic', None, False, ),  # 23
    None,  # 24
    None,  # 25
    None,  # 26
    None,  # 27
    (28, TType.BOOL, 'bUnderline', None, False, ),  # 28
)
all_structs.append(Annotation)
Annotation.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'eType', None, None, ),  # 1
    (2, TType.DOUBLE, 'dXPos', None, None, ),  # 2
    (3, TType.DOUBLE, 'dYPos', None, None, ),  # 3
    (4, TType.DOUBLE, 'dWidth', None, None, ),  # 4
    (5, TType.DOUBLE, 'dHeight', None, None, ),  # 5
    (6, TType.STRING, 'sText', 'UTF8', None, ),  # 6
    (7, TType.STRING, 'sFillColour', 'UTF8', None, ),  # 7
    (8, TType.STRING, 'sLineColour', 'UTF8', None, ),  # 8
    (9, TType.I32, 'iRotation', None, None, ),  # 9
    (10, TType.DOUBLE, 'dLineOpacity', None, None, ),  # 10
    (11, TType.DOUBLE, 'dFillOpacity', None, None, ),  # 11
    (12, TType.I32, 'iOrder', None, None, ),  # 12
    (13, TType.DOUBLE, 'dLineWidth', None, None, ),  # 13
    (14, TType.DOUBLE, 'dFontHeight', None, None, ),  # 14
    (15, TType.STRING, 'sFontName', 'UTF8', None, ),  # 15
    (16, TType.STRING, 'sFontColour', 'UTF8', None, ),  # 16
    (17, TType.STRING, 'sCreatedBy', 'UTF8', "", ),  # 17
    (18, TType.STRING, 'sTimeCreated', 'UTF8', "", ),  # 18
    (19, TType.STRING, 'sModifiedBy', 'UTF8', "", ),  # 19
    (20, TType.STRING, 'sModifiedTime', 'UTF8', "", ),  # 20
    (21, TType.I32, 'iPageLevelID', None, None, ),  # 21
    (22, TType.BOOL, 'bBold', None, False, ),  # 22
    (23, TType.BOOL, 'bItalic', None, False, ),  # 23
    (24, TType.DOUBLE, 'dRotation', None, 0, ),  # 24
    (25, TType.I32, 'eAlign', None, 0, ),  # 25
    (26, TType.I64, 'lModifiedByID', None, 0, ),  # 26
    (27, TType.I64, 'lCreatedByID', None, 0, ),  # 27
    (28, TType.BOOL, 'bUnderline', None, False, ),  # 28
    (29, TType.I64, 'lTextBottom', None, 0, ),  # 29
    (30, TType.DOUBLE, 'dOffsetRotation', None, 0, ),  # 30
    None,  # 31
    None,  # 32
    None,  # 33
    None,  # 34
    None,  # 35
    None,  # 36
    None,  # 37
    None,  # 38
    None,  # 39
    None,  # 40
    None,  # 41
    None,  # 42
    None,  # 43
    None,  # 44
    None,  # 45
    None,  # 46
    None,  # 47
    None,  # 48
    None,  # 49
    (50, TType.STRING, 'sReasonCategory', 'UTF8', None, ),  # 50
    (51, TType.STRING, 'sFoundValue', 'UTF8', None, ),  # 51
    (52, TType.STRING, 'sSearchedValue', 'UTF8', None, ),  # 52
    (53, TType.I32, 'iConfidence', None, None, ),  # 53
    (54, TType.I32, 'eSource', None, 1, ),  # 54
    None,  # 55
    None,  # 56
    None,  # 57
    None,  # 58
    None,  # 59
    None,  # 60
    None,  # 61
    None,  # 62
    None,  # 63
    None,  # 64
    None,  # 65
    None,  # 66
    None,  # 67
    None,  # 68
    None,  # 69
    None,  # 70
    None,  # 71
    None,  # 72
    None,  # 73
    None,  # 74
    None,  # 75
    None,  # 76
    None,  # 77
    None,  # 78
    None,  # 79
    None,  # 80
    None,  # 81
    None,  # 82
    None,  # 83
    None,  # 84
    None,  # 85
    None,  # 86
    None,  # 87
    None,  # 88
    None,  # 89
    None,  # 90
    None,  # 91
    None,  # 92
    None,  # 93
    None,  # 94
    None,  # 95
    None,  # 96
    None,  # 97
    None,  # 98
    None,  # 99
    None,  # 100
    None,  # 101
    None,  # 102
    None,  # 103
    None,  # 104
    (105, TType.BOOL, 'bAutoWrap', None, False, ),  # 105
    None,  # 106
    None,  # 107
    None,  # 108
    None,  # 109
    None,  # 110
    None,  # 111
    None,  # 112
    None,  # 113
    None,  # 114
    None,  # 115
    None,  # 116
    None,  # 117
    None,  # 118
    None,  # 119
    None,  # 120
    None,  # 121
    None,  # 122
    None,  # 123
    None,  # 124
    None,  # 125
    None,  # 126
    None,  # 127
    None,  # 128
    None,  # 129
    None,  # 130
    None,  # 131
    None,  # 132
    None,  # 133
    None,  # 134
    None,  # 135
    None,  # 136
    None,  # 137
    None,  # 138
    None,  # 139
    None,  # 140
    None,  # 141
    None,  # 142
    None,  # 143
    None,  # 144
    None,  # 145
    None,  # 146
    None,  # 147
    None,  # 148
    None,  # 149
    None,  # 150
    None,  # 151
    None,  # 152
    None,  # 153
    None,  # 154
    None,  # 155
    None,  # 156
    None,  # 157
    None,  # 158
    None,  # 159
    None,  # 160
    None,  # 161
    None,  # 162
    None,  # 163
    None,  # 164
    None,  # 165
    None,  # 166
    None,  # 167
    None,  # 168
    None,  # 169
    None,  # 170
    None,  # 171
    None,  # 172
    None,  # 173
    None,  # 174
    None,  # 175
    None,  # 176
    None,  # 177
    None,  # 178
    None,  # 179
    None,  # 180
    None,  # 181
    None,  # 182
    None,  # 183
    None,  # 184
    None,  # 185
    None,  # 186
    None,  # 187
    None,  # 188
    None,  # 189
    None,  # 190
    None,  # 191
    None,  # 192
    None,  # 193
    None,  # 194
    None,  # 195
    None,  # 196
    None,  # 197
    None,  # 198
    None,  # 199
    None,  # 200
    None,  # 201
    None,  # 202
    None,  # 203
    None,  # 204
    None,  # 205
    None,  # 206
    None,  # 207
    None,  # 208
    None,  # 209
    None,  # 210
    None,  # 211
    None,  # 212
    None,  # 213
    None,  # 214
    None,  # 215
    None,  # 216
    None,  # 217
    None,  # 218
    None,  # 219
    None,  # 220
    None,  # 221
    None,  # 222
    None,  # 223
    None,  # 224
    None,  # 225
    None,  # 226
    None,  # 227
    None,  # 228
    None,  # 229
    None,  # 230
    None,  # 231
    None,  # 232
    None,  # 233
    None,  # 234
    None,  # 235
    None,  # 236
    None,  # 237
    None,  # 238
    None,  # 239
    None,  # 240
    None,  # 241
    None,  # 242
    None,  # 243
    None,  # 244
    None,  # 245
    None,  # 246
    None,  # 247
    None,  # 248
    None,  # 249
    None,  # 250
    None,  # 251
    None,  # 252
    None,  # 253
    None,  # 254
    None,  # 255
    None,  # 256
    None,  # 257
    None,  # 258
    None,  # 259
    None,  # 260
    None,  # 261
    None,  # 262
    None,  # 263
    None,  # 264
    None,  # 265
    None,  # 266
    None,  # 267
    None,  # 268
    None,  # 269
    None,  # 270
    None,  # 271
    None,  # 272
    None,  # 273
    None,  # 274
    None,  # 275
    None,  # 276
    None,  # 277
    None,  # 278
    None,  # 279
    None,  # 280
    None,  # 281
    None,  # 282
    None,  # 283
    None,  # 284
    None,  # 285
    None,  # 286
    None,  # 287
    None,  # 288
    None,  # 289
    None,  # 290
    None,  # 291
    None,  # 292
    None,  # 293
    None,  # 294
    None,  # 295
    None,  # 296
    None,  # 297
    None,  # 298
    None,  # 299
    None,  # 300
    None,  # 301
    None,  # 302
    None,  # 303
    None,  # 304
    None,  # 305
    None,  # 306
    None,  # 307
    None,  # 308
    None,  # 309
    None,  # 310
    None,  # 311
    None,  # 312
    None,  # 313
    None,  # 314
    None,  # 315
    None,  # 316
    None,  # 317
    None,  # 318
    None,  # 319
    None,  # 320
    None,  # 321
    None,  # 322
    None,  # 323
    None,  # 324
    None,  # 325
    None,  # 326
    None,  # 327
    None,  # 328
    None,  # 329
    None,  # 330
    None,  # 331
    None,  # 332
    None,  # 333
    None,  # 334
    None,  # 335
    None,  # 336
    None,  # 337
    None,  # 338
    None,  # 339
    None,  # 340
    None,  # 341
    None,  # 342
    None,  # 343
    None,  # 344
    None,  # 345
    None,  # 346
    None,  # 347
    None,  # 348
    None,  # 349
    None,  # 350
    None,  # 351
    None,  # 352
    None,  # 353
    None,  # 354
    None,  # 355
    None,  # 356
    None,  # 357
    None,  # 358
    None,  # 359
    None,  # 360
    None,  # 361
    None,  # 362
    None,  # 363
    None,  # 364
    None,  # 365
    None,  # 366
    None,  # 367
    None,  # 368
    None,  # 369
    None,  # 370
    None,  # 371
    None,  # 372
    None,  # 373
    None,  # 374
    None,  # 375
    None,  # 376
    None,  # 377
    None,  # 378
    None,  # 379
    None,  # 380
    None,  # 381
    None,  # 382
    None,  # 383
    None,  # 384
    None,  # 385
    None,  # 386
    None,  # 387
    None,  # 388
    None,  # 389
    None,  # 390
    None,  # 391
    None,  # 392
    None,  # 393
    None,  # 394
    None,  # 395
    None,  # 396
    None,  # 397
    None,  # 398
    None,  # 399
    None,  # 400
    None,  # 401
    None,  # 402
    None,  # 403
    None,  # 404
    None,  # 405
    None,  # 406
    None,  # 407
    None,  # 408
    None,  # 409
    None,  # 410
    None,  # 411
    None,  # 412
    None,  # 413
    None,  # 414
    None,  # 415
    None,  # 416
    None,  # 417
    None,  # 418
    None,  # 419
    None,  # 420
    None,  # 421
    None,  # 422
    None,  # 423
    None,  # 424
    None,  # 425
    None,  # 426
    None,  # 427
    None,  # 428
    None,  # 429
    None,  # 430
    None,  # 431
    None,  # 432
    None,  # 433
    None,  # 434
    None,  # 435
    None,  # 436
    None,  # 437
    None,  # 438
    None,  # 439
    None,  # 440
    None,  # 441
    None,  # 442
    None,  # 443
    None,  # 444
    None,  # 445
    None,  # 446
    None,  # 447
    None,  # 448
    None,  # 449
    None,  # 450
    None,  # 451
    None,  # 452
    None,  # 453
    None,  # 454
    None,  # 455
    None,  # 456
    None,  # 457
    None,  # 458
    None,  # 459
    None,  # 460
    None,  # 461
    None,  # 462
    None,  # 463
    None,  # 464
    None,  # 465
    None,  # 466
    None,  # 467
    None,  # 468
    None,  # 469
    None,  # 470
    None,  # 471
    None,  # 472
    None,  # 473
    None,  # 474
    None,  # 475
    None,  # 476
    None,  # 477
    None,  # 478
    None,  # 479
    None,  # 480
    None,  # 481
    None,  # 482
    None,  # 483
    None,  # 484
    None,  # 485
    None,  # 486
    None,  # 487
    None,  # 488
    None,  # 489
    None,  # 490
    None,  # 491
    None,  # 492
    None,  # 493
    None,  # 494
    None,  # 495
    None,  # 496
    None,  # 497
    None,  # 498
    None,  # 499
    (500, TType.I64, 'lFormFieldID', None, None, ),  # 500
)
all_structs.append(AnnotationData)
AnnotationData.thrift_spec = (
    None,  # 0
    (1, TType.LIST, 'aAnnots', (TType.STRUCT, [Annotation, None], False), None, ),  # 1
    (2, TType.I32, 'iPageLevelIDCount', None, None, ),  # 2
    (3, TType.I32, 'ePageBlocker', None, 0, ),  # 3
    (4, TType.STRING, 'sPageBlockerColour', 'UTF8', None, ),  # 4
    (5, TType.I64, 'lPageNumber', None, None, ),  # 5
)
all_structs.append(PageAnnotations)
PageAnnotations.thrift_spec = (
    None,  # 0
    (1, TType.I64, 'ID', None, None, ),  # 1
    (2, TType.I64, 'lObjectID', None, None, ),  # 2
    (3, TType.I64, 'lFieldID', None, None, ),  # 3
    (4, TType.I64, 'lSetID', None, None, ),  # 4
    (5, TType.STRING, 'sDocument', 'UTF8', None, ),  # 5
    (6, TType.STRING, 'sPage', 'UTF8', None, ),  # 6
    (7, TType.STRUCT, 'oAnnotData', [AnnotationData, None], None, ),  # 7
)
all_structs.append(AnnotationDateRange)
AnnotationDateRange.thrift_spec = (
    None,  # 0
    (1, TType.STRING, 'sStartDate', 'UTF8', None, ),  # 1
    (2, TType.STRING, 'sEndDate', 'UTF8', None, ),  # 2
)
all_structs.append(AnnotationLimiter)
AnnotationLimiter.thrift_spec = (
    None,  # 0
    (1, TType.SET, 'aCreatedByUserGroups', (TType.I64, None, False), None, ),  # 1
    (2, TType.STRUCT, 'oModifiedDate', [AnnotationDateRange, None], None, ),  # 2
    (3, TType.STRUCT, 'oCreatedDate', [AnnotationDateRange, None], None, ),  # 3
    (4, TType.SET, 'setAnnotationTypes', (TType.I32, None, False), None, ),  # 4
)
all_structs.append(TextImageBBox)
TextImageBBox.thrift_spec = (
    None,  # 0
    (1, TType.I64, 'TopLeftX', None, 0, ),  # 1
    (2, TType.I64, 'TopLeftY', None, 0, ),  # 2
    (3, TType.I64, 'BottomRightX', None, 0, ),  # 3
    (4, TType.I64, 'BottomRightY', None, 0, ),  # 4
)
all_structs.append(TextImageHits)
TextImageHits.thrift_spec = (
    None,  # 0
    (1, TType.STRING, 'image', 'UTF8', None, ),  # 1
    (2, TType.STRUCT, 'page_bbox', [TextImageBBox, None], None, ),  # 2
    (3, TType.I32, 'rotation', None, None, ),  # 3
    (4, TType.LIST, 'hit_bboxes', (TType.STRUCT, [TextImageBBox, None], False), None, ),  # 4
    (5, TType.STRING, 'key', 'UTF8', None, ),  # 5
    (6, TType.DOUBLE, 'confidence', None, None, ),  # 6
)
all_structs.append(RegularExpression)
RegularExpression.thrift_spec = (
    None,  # 0
    (1, TType.STRING, 'Name', 'UTF8', None, ),  # 1
    (2, TType.STRING, 'Expression', 'UTF8', None, ),  # 2
)
all_structs.append(SpreadSheetRedactions)
SpreadSheetRedactions.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'SheetNumber', None, None, ),  # 1
    (2, TType.I32, 'RedactionColour', None, None, ),  # 2
    (3, TType.LIST, 'SelectorList', (TType.STRING, 'UTF8', False), None, ),  # 3
    (4, TType.LIST, 'SearchValues', (TType.STRING, 'UTF8', False), None, ),  # 4
    None,  # 5
    (6, TType.I32, 'ConfidenceThreshold', None, 100, ),  # 6
    None,  # 7
    (8, TType.STRING, 'ReplacementText', 'UTF8', None, ),  # 8
)
all_structs.append(NativeRedactorMessage)
NativeRedactorMessage.thrift_spec = (
    None,  # 0
    (1, TType.I64, 'JobID', None, None, ),  # 1
    (2, TType.I32, 'Type', None, None, ),  # 2
    (3, TType.STRING, 'FeedbackQueue', 'UTF8', None, ),  # 3
    (4, TType.STRING, 'Message', 'UTF8', None, ),  # 4
    (5, TType.I64, 'RecordID', None, None, ),  # 5
    (6, TType.I64, 'ProjectID', None, None, ),  # 6
)
all_structs.append(NativeRedactionResult)
NativeRedactionResult.thrift_spec = (
    None,  # 0
    (1, TType.BOOL, 'Success', None, None, ),  # 1
    (2, TType.STRING, 'Message', 'UTF8', None, ),  # 2
)
all_structs.append(SpreadSheetRedactorMessage)
SpreadSheetRedactorMessage.thrift_spec = (
    None,  # 0
    (1, TType.STRING, 'SourceFile', 'UTF8', None, ),  # 1
    (2, TType.STRING, 'TargetFile', 'UTF8', None, ),  # 2
    (3, TType.STRUCT, 'Redactions', [SpreadSheetRedactions, None], None, ),  # 3
)
all_structs.append(RedactionList)
RedactionList.thrift_spec = (
    None,  # 0
    (1, TType.I64, 'lID', None, None, ),  # 1
    (2, TType.STRING, 'sName', 'UTF8', None, ),  # 2
)
all_structs.append(RedactionListItem)
RedactionListItem.thrift_spec = (
    None,  # 0
    (1, TType.I64, 'lID', None, None, ),  # 1
    (2, TType.I64, 'lListID', None, None, ),  # 2
    (3, TType.STRING, 'sText', 'UTF8', None, ),  # 3
    (4, TType.STRING, 'sReason', 'UTF8', None, ),  # 4
)
fix_spec(all_structs)
del all_structs
