#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys

from thrift.transport import TTransport
all_structs = []


class Color(object):
    NOT_APPLICABLE = 0
    BLACK = 1
    BLUE = 2
    FUCHISA = 3
    GRAY = 4
    GREEN = 5
    AQUA = 6
    LIME = 7
    MAROON = 8
    NAVY = 9
    OLIVE = 10
    PURPLE = 11
    RED = 12
    SILVER = 13
    TEAL = 14
    WHITE = 15
    YELLOW = 16
    MANILA = 17
    ORANGE = 18

    _VALUES_TO_NAMES = {
        0: "NOT_APPLICABLE",
        1: "BLACK",
        2: "BLUE",
        3: "FUCHISA",
        4: "GRAY",
        5: "GREEN",
        6: "AQUA",
        7: "LIME",
        8: "MAROON",
        9: "NAVY",
        10: "OLIVE",
        11: "PURPLE",
        12: "RED",
        13: "SILVER",
        14: "TEAL",
        15: "WHITE",
        16: "YELLOW",
        17: "MANILA",
        18: "ORANGE",
    }

    _NAMES_TO_VALUES = {
        "NOT_APPLICABLE": 0,
        "BLACK": 1,
        "BLUE": 2,
        "FUCHISA": 3,
        "GRAY": 4,
        "GREEN": 5,
        "AQUA": 6,
        "LIME": 7,
        "MAROON": 8,
        "NAVY": 9,
        "OLIVE": 10,
        "PURPLE": 11,
        "RED": 12,
        "SILVER": 13,
        "TEAL": 14,
        "WHITE": 15,
        "YELLOW": 16,
        "MANILA": 17,
        "ORANGE": 18,
    }
fix_spec(all_structs)
del all_structs
